---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: %appName%
  name: %appName%-service
  namespace: %namespace%
spec:
  ports:
  - port: 443
    name: https
    targetPort: 443
    protocol: TCP
  - port: 80
    name : http
    targetPort: 80
    protocol: TCP
  selector:
    app: %appName%
  type: LoadBalancer
