version: '2'
services:
    %srvname%:
        image: %dtr/image:version%
        ports:
            - 443
        labels:
          interlock.hostname: "%endpoint_name%"
          interlock.domain:   "%endpoint_domain%"
          interlock.ssl: "1"
          interlock.ssl_cert: "/certs/cert.pem"
          interlock.ssl_cert_key: "/certs/key.pem"
          interlock.ssl_backend: "1"