---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: %appName%
  name: %appName%-service
  namespace: %namespace%
spec:
  ports:
  - port: 443
  selector:
    app: %appName%
  type: LoadBalancer